name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install pytest
        run: pip install pytest

      - name: Run tests
        run: pytest

      - name: Show success message
        run: echo "GitHub Actions CI completed successfully!"